apply plugin: "io.gitlab.arturbosch.detekt"

// The type-safe accessors (libs.xxx) are not available in the script plugins, use the
// VersionCatalogsExtension instead.
def libsCatalog = project.rootProject.extensions
    .getByType(org.gradle.api.artifacts.VersionCatalogsExtension)
    .named("libs")

detekt {
    source.setFrom(files("src"))

    // Use the default config as the baseline and apply the project specific overrides on top.
    buildUponDefaultConfig = true
    config.setFrom(files("$rootDir/config/detekt/detekt-config.yml"))

    // Prevent the build to fail if the threshold set by build.maxIssues is exceeded, when the
    // property detektIgnoreFailures is available. This should be used when running a sanity check
    // on all the modules.
    ignoreFailures = project.hasProperty("detektIgnoreFailures")

    // Apply the auto-correction of the formatting rules when the property is available.
    autoCorrect = project.hasProperty("detektAutoCorrect")
}

dependencies {
    detektPlugins libsCatalog.findLibrary("detekt-formatting").get()
}

tasks.named("detekt") {
    exclude("resources/")
    exclude("build/")
    exclude("tmp/")

    reports {
        xml.required = true
        html.required = true
    }
}
