import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id "com.android.application"
    alias(libs.plugins.kotlin.compose)
}

class AppVersions {
    int versionCode
    String versionName
}

def loadAppVersions() {
    def props = loadProperties("$rootDir/appVersion.properties")
    def appVersions = new AppVersions()
    appVersions.versionCode = props["version.code"] as int
    appVersions.versionName = props["version.name"]
    return appVersions
}

def appVersions = loadAppVersions()

android {
    namespace "com.github.wangyung.persona.app"
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "com.github.wangyung.persona.app"
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        versionCode appVersions.versionCode
        versionName appVersions.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // Configure only for each module that uses Java 8
    // language features (either in its source code or
    // through dependencies).
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }



    buildFeatures {
        viewBinding true
        compose true
    }

}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
}

dependencies {

    implementation project(":persona-json-serialization-kotlinx")
    implementation project(":persona-compose")
    implementation project(":persona-core")

    implementation libs.kotlin.stdlib
    implementation libs.kotlin.reflect
    implementation libs.coroutines.core
    implementation libs.coroutines.android

    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.google.material

    // Jetpack Compose
    implementation libs.compose.activity
    implementation platform(libs.compose.bom)
    implementation libs.compose.material
    implementation libs.compose.ui
    implementation libs.compose.uiTooling
    implementation libs.compose.constraintlayout
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.compose.navigation

    testImplementation libs.androidx.test.junit
    testImplementation libs.junit
    testImplementation libs.kotlin.test.junit
    testImplementation libs.coroutines.test
    testImplementation libs.compose.uiTestJunit4
}

