plugins {
    id "com.android.library"
    id "maven-publish"
}

def loadLibVersion() {
    def props = loadProperties("$projectDir/version.properties")
    return props["version.name"]
}

def libVersion = loadLibVersion()

android {
    namespace "com.github.wangyung.persona"
    resourcePrefix "persona"

    compileSdk libs.versions.compileSdk.get().toInteger()
    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    // Configure only for each module that uses Java 8
    // language features (either in its source code or
    // through dependencies).
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }



    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    // The variants that can be consumed by the maven publications below.
    publishing {
        singleVariant("release")
        singleVariant("debug")
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
    }
}

dependencies {

    implementation libs.kotlin.stdlib
    implementation libs.coroutines.core
    implementation libs.coroutines.android

    implementation libs.androidx.annotation

    testImplementation libs.androidx.test.junit
    testImplementation libs.junit
    testImplementation libs.kotlin.test.junit
    testImplementation libs.coroutines.test
    testImplementation libs.robolectric
}

// Because the components are created only during the afterEvaluate phase, you must
// configure your publications using the afterEvaluate() lifecycle method.
afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                // Applies the component for the release build variant.
                from components.release

                // You can then customize attributes of the publication as shown below.
                groupId = "com.github.wangyung"
                artifactId = "persona"
                version = libVersion
            }
            // Creates a Maven publication called “debug”.
            debug(MavenPublication) {
                // Applies the component for the debug build variant.
                from components.debug

                groupId = "com.github.wangyung"
                artifactId = "persona-debug"
                version = libVersion
            }
        }
    }
}
